- kre-py/src/kre_runner.py
relates https://github.com/konstellation-io/kre/issues/410
> fix: logging milliseconds in python runners

- kre-py/Pipfile
- kre-py/Pipfile.lock
- kre-py/requirements.txt
This PR adds a new library to work with email bodies and clean html texts.
> feat(kre-py): add new library html2text to clean data.

- kre-py/Dockerfile
- kre-py/Pipfile
- kre-py/Pipfile.lock
- kre-py/install_stopwords.py
This PR generate base runner images to use on different projects or workflows. 
The new image runner doesn't have cuda installed.
> feat: New base runners

- kre-py/Dockerfile
Hi Team,
This is a fix to see the logs from the kre ui.
> fix(kre-py): Logging issues

- .github/workflows/kre-py_tests.yaml
- kre-py/Dockerfile
- kre-py/Pipfile
- kre-py/Pipfile.lock
- kre-py/sonar-project.properties
- kre-py/src/config.py
- kre-py/src/kre_runner.py
- kre-py/src/main_test.py
- kre-py/test_assets/docker-compose.yml
- kre-py/test_assets/influx/setup_database.sh
This PR add testing on the kre-py runner:
- The runner is built on docker-compose.
- The test is executed on PR and every push in all branches monitoring changes on a set of directories.
> feat: add test on kre-py runner

- kre-py/Pipfile
- kre-py/Pipfile.lock
- kre-py/src/kre_nats_msg_pb2.py
- kre-py/test_assets/myvol/src/node/public_input_for_testing_pb2.py
Update protobuf version from `3.13.0` to `3.19.4` for the kre-py runners.
> feat(kre-py): Update protobuf

- kre-py/README.md
BREAKING CHANGE: this runner version is only compatible with multiruntime KRE
> fix: new major in kre-py runner

- kre-go/README.md
> feat(kre-go): add compatibility with NATS jetstream on kre-go

- kre-py/README.md
> feat(kre-py): add compatibility with NATS jetstream on kre-py

- kre-entrypoint/README.md
> feat(kre-entrypoint): add compatibility with NATS jetstream on kre-entrypoint

- krt-files-downloader/README.md
> feat(krt-files-downloader): add compatibility with NATS jetstream

- kre-py/src/main.py
kre-py runner was not recovering correctly when it couldn't connect to jetstream stream.
Make kre-py exit execution when not subscribing correctly so it tries subscription again.
> fix(kre-py): jetstream subscription error

- kre-go/context_test.go
We wanted to cleanup some redundant code in the kre-go context tests.
- Deleted env config
- Fixed t.Fatal warnings
> upgrade(kre-go): Refactor context tests

- Makefile
There are some common commands used to develop in the repository that needs to be documented
Creates a `Makefile` to document and facilitate the use of the commands.
> makefile: add makefile with common goals

- kre-py/src/main.py
We detected a broken flux in where if the handler execution returns error, the request message is not acknowledged. Meaning requests that invoke exceptions are processed forever.
- Ack messages when exception is captured as well
>  fix(kre-py): Infinte ack loop when error 

- .github/workflows/kre-py_tests.yaml
- kre-entrypoint/src/kre_entrypoint.py
- kre-py/Pipfile
- kre-py/Pipfile.lock
- kre-py/src/conftest.py
- kre-py/src/context_measurement.py
- kre-py/src/test_context_data.py
- kre-py/src/test_context_measurement.py
As the Python tests were inherited from legacy code, they need to be reviewed and updated.
* Python integration tests have been deprecated
* Unit tests have been created
* GitHub actions related to the Python test execution have been updated
* Some minor refactors based on the Sonar Analysis
> feat(kre-py): Add python unit tests

- kre-py/src/config.py
BREAKING CHANGE: change python runner to support krt v2
> fix(kre-py): revert changes to config

- .github/workflows/kre-exitpoint_release.yaml
- kre-exitpoint/go.mod
- kre-exitpoint/go.sum
Exitpoint docker image needs to be built and released in CI workflow
Adds a new github workflow to build & release exitpoint docker image
> ci: release exitpoint

- README.md
Configure SonarCloud to analyze the KRE-runners.
We need to have more visibility on the status of the project and the quality of the new code.
This is why we need to configure the SonarCloud analysis.
I've also renamed the workflow files to match a common pattern and to be more structured
> Sonarcloud integration

- .github/workflows/build-release.yaml
- .github/workflows/new-release.yaml
- kre-py-objstore/Dockerfile
- kre-py-objstore/Pipfile
- kre-py-objstore/Pipfile.lock
- kre-py-objstore/README.md
Add new runtime kre-py-objstore
Add new runtime based on kre-py that introduces new nats library with new object store functionallity
> feat(kre-py-objstore): Add new runtime

- kre-py-objstore/package.json
- package.json
Add kre-py-objstore to semantic-release config to semantic-release config
Fixes automatic releases for kre-py-objstore
> ci(kre-py-objstore): add package to semantic-release config

- kre-py/src/config.py
> refactor(kre-py): deprecate is exitpoint config

- kre-py/Pipfile
- kre-py/Pipfile.lock
> fix(kre-py): update protobuf version

- kre-go/runner.go
Compression protocols will now take the maximum permitted payload size from NATS configuration.
Users wanted to send payloads larger than 1MB of size.
> fix(kre-go): fix hardcoded value for compressing messages

- kre-py/src/context_configuration.py
- kre-py/src/test_context_configuration.py
> fix(kre-py): replace scope enum with str

- kre-go/internal/errors/errors.go
- kre-go/runner.go
> fix(kre-go): fix errMsgTooBig

- .github/workflows/new-release.yaml
Fixes multiple workflow runs when New Release workflow is executed
> ci: fix New Release workflow workflow_run types

- kre-go/runner.go
> fix(kre-go): make init function optional

- .github/workflows/kre-go_tests.yaml
- go.work.sum
- kre-go/context_objectstore.go
- kre-go/context_objectstore_test.go
- kre-go/sonar-project.properties
The users have asked for helper methods to list and delete objects from the object store.
The next changes add methods for listing and deleting objects, with an optional filter that receives a regexp expression to delete/list the objects.
> Add object store methods for listing and removing objects

- kre-go/context.go
- kre-go/context_configuration.go
- kre-go/context_database.go
- kre-go/context_database_test.go
- kre-go/context_measurement.go
- kre-go/context_objectstore.go
- kre-go/context_objectstore_test.go
- kre-go/context_prediction.go
- kre-go/runner.go
Handler context now uses interfaces.
Help users with theirs testing suites, so they can mock specific handler context utilities.
> feat(kre-go): handler context now uses interfaces

- kre-entrypoint/src/kre_entrypoint.py
- Make ack after unsubscribe
Messages are not being ack in the entrypoint.
> fix(entrypoint): ack for messages

- e2e/scripts/build_go_node.sh
- kre-entrypoint/src/kre_entrypoint.py
- Upon exception we will unsubscribe
- Added flags to go build for e2e testing
If an exception occurs, ephemeral subscriptions will stay active, consuming resources forever. Also go builds for e2e have incompatibilities if built from different os.
> fix(entrypoint): fix unsubscription upon exception

- kre-entrypoint/src/kre_entrypoint.py
> fix(kre-entrypoint): avoid unsubscribe multiple times

- kre-entrypoint/src/kre_entrypoint.py
- kre-py/src/config.py
- kre-py/src/main.py
> Add max pending ACKs to kre-py

- kre-entrypoint/src/kre_entrypoint.py
- kre-go/config/config.go
- kre-go/main.go
> Add max pending ACK to the nats consumer configuration
